creates gql schema
Dragon-Glass/new-obsidian-demo pull request #2
Opened 2020-12-31 20:59 UTC by dsymiller

her is the initial draft of the gql schema for the new demo app

2020-12-31 21:32 UTC, lourentflores requested changes

2020-12-31 21:32 UTC, lourentflores commented on server/schema.ts
> +    acrorId: ID!
typo, should be actorId

2020-12-31 22:20 UTC, dsymiller commented on server/schema.ts
> +    acrorId: ID!
fixed

2021-01-01 16:10 UTC, lourentflores approved these changes

2021-01-01 17:20 UTC, merged